name: Build and Push

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]

jobs:
  build_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - name: build
        uses: actions/checkout@v4
        run: |
          node --version
          npm ci
          npm run deploy
